### ISSUE TITLE
Export Does not work with Python 3.5 3.7 3.8 or 3.9 (did not test others)

### ISSUE THREAD

**Issue by ensingerphilipp** [novitae/sterraxcyl#14]
Traceback (most recent call last):
  File "/home/exspir3/.local/bin/sterra", line 8, in <module>
    sys.exit(main())
  File "/home/exspir3/.local/lib/python3.8/site-packages/sterra/core.py", line 430, in main
    ret = globals()[module.upper()](**kwargs)
  File "/home/exspir3/.local/lib/python3.8/site-packages/sterra/core.py", line 87, in EXPORT
    scrape(t,l)
  File "/home/exspir3/.local/lib/python3.8/site-packages/sterra/core.py", line 38, in scrape
    _.p(f"""{username}'s {targlist} usernames file exported under id: {str(bold(exporter([{"username":usn} for usn in flist],_,**kwargs)()))}""",logo=logo_to_choose)
TypeError: __init__() missing 2 required positional arguments: 'file_path' and 'Format'

**Comment by novitae** [comment]
Not coming from your python, it comes from the program itself.
Sorry for the inconvenience, im working right now on a new version where this issue will be fixed :)

**Comment by novitae** [comment]
Could you write me down the command you entered to end up on this bug (obviously don't show the target's username and your credentials/sessionid) ?

**Comment by ensingerphilipp** [comment]
sterra export -u XXX-ssid XXXX -t both --only-usernames

thanks for fixing :)

**Comment by novitae** [comment]
The issue have been fixed https://github.com/novitae/sterraxcyl/commit/e1a6d85db0a6ea2176f8fdeaf5c549cf9c06a06b, you can update, it should work.
(`pip install sterra --upgrade`)
